config/routes.rb
ProjectManager::Application.routes.draw do
    
    root :to => "sessions#new"
    
    resources :sessions
    resources :users
    
    match 'login' => 'sessions#new'
    match 'logout' => 'sessions#destroy'
    match 'signup' => 'users#new'
    match 'calendar/:type/:id' => 'sessions#calendar'
    match 'search' => 'sessions#index'
    match 'budget/:id' => 'projects#budget'
    match 'forgot_password' => 'sessions#forgot_password'
    match 'confirm_code/:confirmation_code' => 'sessions#confirm_code'
    match 'send_password' => 'sessions#send_password'
    match 'users/:id/change_password' => 'users#change_password'
    resources :tasks
    resources :projects

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <% unless yield(:title).blank? %>
    <title><%= (yield(:title)).to_s + " - Project Visualization Application" %></title>
  <% else %>
    <title>Project Visualization Application</title>
  <% end %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br /><br />
  <h1>Project Visualization Application</h1>
  <div id="header">
    <div id="user_menu">
      <% if current_user.present? %>
        <ul id="nav" class="drop">
          <li><%= "#{current_user.name} v" %>
            <ul>
	      <li><%= link_to "Home", "/" %></li>
              <li><%= link_to "My Calendar", "/calendar/user/#{current_user.id}" %></li>
	      <li><%= link_to "Change Password", "/users/#{current_user.id}/change_password" %></li>
              <li><%= link_to "Logout", "/logout" %></li>
            </ul>
          </li>
	</ul>
	<% if current_user.role == 8 %>
	  <ul id="nav" class="drop">
	    <li>Admin v
	      <ul>
		<li><%= link_to "Projects Management", projects_path %></li>
		<li><%= link_to "Tasks Management", tasks_path %></li>
		<li><%= link_to "User Management", users_path %></li>
	      </ul>
	    </li>
	  </ul>
	<% end %>
        <% else %>
        <div id="login_bar">
        <ul>
          <li><%= link_to "Login", "/login" %></li>
          <li><%= link_to "Signup", "/signup" %></li>         
        </ul>
        </div>
        <% end %>
      </div>
    </div>
    <div id="container">
    <div id="nav_menu">
      <ul>
        <li>
          <%= form_tag sessions_path, :method => 'get', :id => 'nav_menu_search' do %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          <% end %>
        </li>
        <li><%= link_to "Advanced Search", "/search" %></li>
      </ul>
    </div>
    <div id="message_of_the_day"></div>
    <div id="actual_body">
  <% if current_user.present? && current_user.role == 8 %>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  <% else %>
    You are not authorized to view this page!
  <% end %>
  </div>
  <a href="http://projectmanagerapp.herokuapp.com"><div id="banner"></div></a>
  <div id="footer"> Made by Kevin Chen, Nicole Hansen, Shabaz Gulam</div>
  </div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% unless yield(:title).blank? %>
    <title><%= (yield(:title)).to_s + " - Project Visualization Application" %></title>
  <% else %>
    <title>Project Visualization Application</title>
  <% end %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br /><br />
  <h1>Project Visualization Application</h1>
  <div id="header">
    <div id="user_menu">
      <% if current_user.present? %>
        <ul id="nav" class="drop">
          <li><%= "#{current_user.name} v" %>
            <ul>
	      <li><%= link_to "Home", "/" %></li>
              <li><%= link_to "My Calendar", "/calendar/user/#{current_user.id}" %></li>
	      <li><%= link_to "Change Password", "/users/#{current_user.id}/change_password" %></li>
              <li><%= link_to "Logout", "/logout" %></li>
            </ul>
          </li>
	</ul>
	<% if current_user.role == 8 %>
	  <ul id="nav" class="drop">
	    <li>Admin v
	      <ul>
		<li><%= link_to "Projects Management", projects_path %></li>
		<li><%= link_to "Tasks Management", tasks_path %></li>
		<li><%= link_to "User Management", users_path %></li>
	      </ul>
	    </li>
	  </ul>
	<% end %>
        <% else %>
        <div id="login_bar">
        <ul>
          <li><%= link_to "Login", "/login" %></li>
          <li><%= link_to "Signup", "/signup" %></li>         
        </ul>
        </div>
        <% end %>
      </div>
    </div>
    <div id="container">
    <div id="nav_menu">
      <ul>
        <li>
          <%= form_tag sessions_path, :method => 'get', :id => 'nav_menu_search' do %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          <% end %>
        </li>
        <li><%= link_to "Advanced Search", "/search" %></li>
      </ul>
    </div>
    <div id="message_of_the_day"></div>
    <div id="actual_body">
      <% if current_user.present? %>
        <p id="notice"><%= notice %></p>
        <p id="alert"><%= alert %></p>
        <%= yield %>
      <% else %>
        You must be logged in to view this page!
      <% end %>
    </div>
    <a href="http://projectmanagerapp.herokuapp.com"><div id="banner"></div></a>
    <div id="footer"> Made by Kevin Chen, Nicole Hansen, Shabaz Gulam</div>
  </div>
</body>
</html>

app/views/layouts/public.html.erb
<html>
<head>
  <% unless yield(:title).blank? %>
    <title><%= (yield(:title)).to_s + " - Project Visualization Application" %></title>
  <% else %>
    <title>Project Visualization Application</title>
  <% end %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br /><br />
  <h1>Project Visualization Application</h1>
  <div id="header">
    <div id="user_menu">
      <% if current_user.present? %>
        <ul id="nav" class="drop">
          <li><%= "#{current_user.name} v" %>
            <ul>
	      <li><%= link_to "Home", "/" %></li>
              <li><%= link_to "My Calendar", "/calendar/user/#{current_user.id}" %></li>
	      <li><%= link_to "Change Password", "/users/#{current_user.id}/change_password" %></li>
              <li><%= link_to "Logout", "/logout" %></li>
            </ul>
          </li>
	</ul>
	<% if current_user.role == 8 %>
	  <ul id="nav" class="drop">
	    <li>Admin v
	      <ul>
		<li><%= link_to "Projects Management", projects_path %></li>
		<li><%= link_to "Tasks Management", tasks_path %></li>
		<li><%= link_to "User Management", users_path %></li>
	      </ul>
	    </li>
	  </ul>
	<% end %>
        <% else %>
        <div id="login_bar">
        <ul>
          <li><%= link_to "Login", "/login" %></li>
          <li><%= link_to "Signup", "/signup" %></li>         
        </ul>
        </div>
        <% end %>
      </div>
    </div>
  <div id="container">
    <div id="nav_menu">
      <ul>
        <li>
          <%= form_tag sessions_path, :method => 'get', :id => 'nav_menu_search' do %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          <% end %>
        </li>
        <li><%= link_to "Advanced Search", "/search" %></li>
      </ul>
    </div>
    <div id="message_of_the_day"></div>
  <div id="actual_body">
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  </div>
  <a href="http://projectmanagerapp.herokuapp.com"><div id="banner"></div></a>
  <div id="footer">Made by Kevin Chen, Nicole Hansen, Shabaz Gulam</div>
  </div>
</body>
</html>